### ISSUE TITLE
Did this tree boot ?

### ISSUE THREAD

**Issue by sooorajjj** [SmallPP420/test_WSP_sprout#1]
Im also working on a mt6761 device i was able to get the device till boot animation stage

**Comment by SmallPP420** [comment]
This tree didn't boot but I do have a working tree :) 

https://GitHub.com/TeamWin/android_device_Nokia_WSP_Sprout

**Comment by SmallPP420** [comment]
No these trees don't work ;(

**Comment by SmallPP420** [comment]
I didn't even get to boot animation stage

**Comment by SmallPP420** [comment]
Maybe u could provide a logcat and I could try help u

**Comment by sooorajjj** [comment]
Just got the device booting 
![Uploading 2B8099B5-A0B9-4916-887C-E3463809740D.jpeg…]()

**Comment by SmallPP420** [comment]
Amazing! I'm happy for you :)

**Comment by SmallPP420** [comment]
If u were able to upload the tree, can u? Cause I want to use it as a base to get it booting on my device thanks in advance

**Comment by SmallPP420** [comment]
Obviously I will give credits
